# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:6
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo
    branches:
      only:
        - master
    steps:
      - checkout

      - run: |
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent)
          ssh-add ~/.ssh/id_rsa
          cp .travis/ssh_config ~/.ssh/config

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: sudo npm install -g gitbook-cli

      - run: gitbook install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: gitbook build

      - run: |
          cd _book
          git config --global user.name 'wangyf'
          git config --global user.email 'zgtjwyftc@gmail.com'
          git init
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force "git@github.com:MasterStudio/MasterWechatApp.git" master:gh-pages
          git config --global user.name 'evanwang'
          git config --global user.email 'evan.wang.master@gmail.com'
          git push --force "git@git.coding.net:MasterStudio/MasterWechatApp.git" master:coding-pages
